### ISSUE TITLE
Настройка интеграции

### ISSUE THREAD

**Issue by RykovDC** [lizardsystems/hass-tnse#1]
После ввода логина и пароля интеграция ничего не предлагает 
![image](https://github.com/lizardsystems/hass-tnse/assets/139807719/6d7ede5c-f414-4466-95ac-ad44fef72023)

**Comment by vzagorovskiy** [comment]
Версия HA Какая?

**Comment by RykovDC** [comment]
![image](https://github.com/lizardsystems/hass-tnse/assets/139807719/bc753693-7bf6-4d33-9109-34a6de9cbf64)

**Comment by vzagorovskiy** [comment]
Похоже вы не ту интееграцию установили

наверное вот установили hass-tns-energo - https://github.com/alryaz/hass-tns-energo

hass-tnse выглядит вот так

![image](https://github.com/lizardsystems/hass-tnse/assets/4923679/c774f5c9-dee9-4c7e-b173-80d8f9adc8ab)

**Comment by RykovDC** [comment]
Нет, та что на вашем скрине у меня стоит и прекрасно работает. А вашу я пытаюсь поставить по ссылке из описания.
![image](https://github.com/lizardsystems/hass-tnse/assets/139807719/4dee0c74-b936-491a-bd88-d604ab74a1f5)
![image](https://github.com/lizardsystems/hass-tnse/assets/139807719/d17bad60-c9c3-47d9-b8a1-97887ed2a05e)

**Comment by vzagorovskiy** [comment]
я не знаю что вы запускаете.
Интеграция hass-tnse не запрашивает пароль и никогда не запрашивала.

Зпрашивает только лицевой счет как я и показал на скрине

ссылка 

https://my.home-assistant.io/redirect/config_flow_start/?domain=tns_energo

Запрос HA

![image](https://github.com/lizardsystems/hass-tnse/assets/4923679/a988dddd-59d0-4efa-aa2d-a6f45894c729)


Запуск настройки

![image](https://github.com/lizardsystems/hass-tnse/assets/4923679/2ab0efa5-42a7-4129-8f57-187484dfd797)

**Comment by RykovDC** [comment]
https://github.com/lizardsystems/hass-tnse/assets/139807719/22e3efbc-f4e0-43cf-8ad1-267e7fbb803c

**Comment by vzagorovskiy** [comment]
все верно. У вас запускается интеграция https://github.com/alryaz/hass-tns-energo

hass-tnse в HACS еще не добавлен.

https://github.com/hacs/default/pull/2386

чтобы запускалась эта интеграция нужно добавить пользовательский репозиторий, 

выполните пункт установка инструкции

и тогда он будет доступен

![image](https://github.com/lizardsystems/hass-tnse/assets/4923679/7015816f-23c5-4034-92b6-0002dfc86d9c)
